#!/usr/bin/env sh

echo 'Running post-merge hook'
eval $(op signin)
find $HOME/.config -type f -iname "*.env" -exec sh -c "op item get ansible-vault --fields password | ansible-vault encrypt {} --vault-password-file=/bin/cat" \;
